#
# DO NOT EDIT THIS FILE DIRECTLY -- this is the SOURCE TEMPLATE in
# agentscore/pay. The publish workflow substitutes the npm tarball URL
# and sha256 and commits the rendered file into agentscore/homebrew-tap
# on each release. Homebrew derives the version from the URL.
#
class AgentscorePay < Formula
  desc "CLI wallet for one-shell-command agent payments (x402 + MPP)"
  homepage "https://agentscore.sh"
  url "https://registry.npmjs.org/@agent-score/pay/-/pay-0.1.0.tgz"
  sha256 "228ab161d3a23599f9643c87f8c1bf9f5059991acc983e5eddda57b86719e324"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/agentscore-pay --version"))
  end
end
