#
# DO NOT EDIT THIS FILE DIRECTLY -- this is the SOURCE TEMPLATE in
# agentscore/pay. The publish workflow substitutes the npm tarball URL
# and sha256 and commits the rendered file into agentscore/homebrew-tap
# on each release. Homebrew derives the version from the URL.
#
class AgentscorePay < Formula
  desc "CLI wallet for one-shell-command agent payments (x402 + MPP)"
  homepage "https://www.agentscore.com"
  url "https://registry.npmjs.org/@agent-score/pay/-/pay-0.4.4.tgz"
  sha256 "143ddb39641d969ed7d92da71363d7b33e80925d5d84f05d2be5e24f37e6a1b4"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/agentscore-pay --version"))
  end
end
